import '@mantine/core/styles.css';
import "./globals.css";
import { ColorSchemeScript } from '@mantine/core';
import {Providers} from "@/app/providers"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

      <html lang="en" suppressHydrationWarning>
        <head>
          <ColorSchemeScript />
        </head>
        <body>
          <Providers>
            {children}
          </Providers>
        </body>
      </html>
  );
}
